### ISSUE TITLE
There are still things wrong with the file-level license declaration fields

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#709]
**Issue Type: Bug**

**Issue Description:**

I was trying to curate the license for a specific file on a component. Two strange things have happened when I try to do this:

Firstly, if you try to curate a file that already has an SPDX expression with multiple conjunctive / disjunctive operators (i.e SPDX _"Apache-2.0 **AND** GPL-1.0-or-later **AND** LGPL-2.0-or-later"_) and try to change to _"Apache-2.0 **OR** LGPL-3.0-or-later"_ instead, CD just appends it to the existing expression. This happens regardless of if you use the editor to build the expression or just type it in letter-by-letter. The result and steps to reproduce are formalized below:

Existing data: _"Apache-2.0 **AND** GPL-1.0-or-later **AND** LGPL-2.0-or-later"_

<img width="669" alt="1" src="https://user-images.githubusercontent.com/31491646/57650654-25aeff00-7580-11e9-9749-7fbda275e3a3.png">

User's input data (via SPDX expression editor): _"Apache-2.0 **OR** LGPL-3.0-or-later"_

<img width="674" alt="2" src="https://user-images.githubusercontent.com/31491646/57650661-2b0c4980-7580-11e9-9f0c-c86f1085cccf.png">

Result data: <img width="788" alt="4" src="https://user-images.githubusercontent.com/31491646/57650715-45debe00-7580-11e9-9b99-c2135c64160e.png">

<img width="673" alt="3" src="https://user-images.githubusercontent.com/31491646/57650734-4d05cc00-7580-11e9-8578-7a8e980202aa.png">

And secondly, in some cases if you try to click on the "pencil" edit field after doing enter in SPDX expressions like the above, the page will go completely blank!

Tested in Google Chrome (64-bit)

**Comment by storrisi** [comment]
This seems to be the same error mentioned in #689

We are going to investigate on this problem on the service side.

Thanks.

**Comment by ignacionr** [comment]
The first part of this is taken care of by https://github.com/clearlydefined/service/pull/530 ; second part (blank screen when using pencil) remains.

**Comment by storrisi** [comment]
Blank screen problem has been fixed in https://github.com/clearlydefined/website/pull/695 , hence once the service implementation will be merged, we can consider this one as closed.

**Comment by bduranc** [comment]
@storrisi I don't see either fixed in prod yet. I will assume this is because they have not been merged yet.

I'll keep my eyes open for when they are :)

**Comment by bduranc** [comment]
@storrisi : More weird behavior: When I add a source location, it now modifies the license field too. 

Please see following component: https://clearlydefined.io/definitions/pypi/pypi/-/Unidecode/1.0.23

I go to the Source Location box and enter the following: user/org = "avian2", repo = "unidecode", commit/version = "unidecode-1.0.23". I enter in the text and then select the drop-down recommendation for each field.

When I click OK, it appends SPDX: "GPL-2.0-only" to the Declared License field. In the end, it looks like the below:

<img width="382" alt="2019-05-23_11-44-08" src="https://user-images.githubusercontent.com/31491646/58279892-5c410280-7d54-11e9-9a98-fdc1a6fb1b41.png">

Do you get the same behavior on your end?

If yes, we need to bump this up in priority if we haven't already because it affects people's ability to do curations.

**Comment by storrisi** [comment]
Thank for addressing this. 
Unfortunately those data are returned from the backend so we should investigate what happens there. I suggest @ignacior to take a look soon.

**Comment by ignacionr** [comment]
This should be resolved by incorporating @dabutvin comment here https://github.com/clearlydefined/service/pull/530#discussion_r286164619 ; I am working on it.

**Comment by royaljust** [comment]
There is also still an issue with flipping ANDs to ORs on the UI -- it can't be done. Not sure if the above solves it and we're just waiting for it to be merged into production, but I thought I'd call it out just in case.

1. License detects BSD-3-Clause AND GPL-2.0.
![image](https://user-images.githubusercontent.com/36014796/58322375-c7d7ae00-7dee-11e9-99f7-e5aeba9507f1.png)

2. User tries to change to BSD-3-Clause OR GPL-2.0 (either by free form text edit or by using the expression generator)
![image](https://user-images.githubusercontent.com/36014796/58322451-04a3a500-7def-11e9-9ac8-d85bc04e7d3a.png)
![image](https://user-images.githubusercontent.com/36014796/58322531-2f8df900-7def-11e9-927b-55718d0dfbc6.png)

3. Nothing happens.  The AND remains.
![image](https://user-images.githubusercontent.com/36014796/58322585-5fd59780-7def-11e9-98d2-a327d5ec5854.png)

**Comment by storrisi** [comment]
@royaljust probably the problem that you mentioned is a website issue. Will check. Thanks.

**Comment by storrisi** [comment]
I can confirm that the website sends to the service the correct information with the proper conjunction "OR" or "AND", but the returned data doesn't contain the change.
I guess that the implementation in https://github.com/clearlydefined/service/pull/530#discussion_r286164619 will fix also this problem.

@ignacionr could you confirm this?

**Comment by dabutvin** [comment]
this is now fixed in production. Please verify and open a new issue if there are further problems.

Regarding the license changing when you edit the source. This is a result of using a new algorithm to simplify the declared license expression and should be fine to submit with your curation.
